baseURL = "https://gp1.netlify.app"
title = "GP1 Blog"
theme = "hugo-coder"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
enableRobotsTXT = true
canonifyURLs = true
enableGitInfo = true
enableEmoji = true
paginate = 9999
pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = false
pluralizelisttitles = false
FootnoteReturnLinkContents = "↑"

[markup.goldmark.renderer]
    unsafe= true

[outputs]
  page     = ["HTML", "AMP"]
  home     = ["HTML", "RSS"]
  section  = ["HTML"]
  taxonomyTerm = ["HTML"]
  taxonomy = ["HTML"]

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
  author = "authors"

[params]
    author = "GP1 Blog"
    description = "GP1 Blog"
    keywords = "blog,developer,personal"
    avatarURL = "images/avatar.jpg"
    header = "GP1 Blog"
    dateFormat = "2006-01-02"
    since = 2022
    github = "StarShangGP1"
    favicon_root_path = "images/ico"
    hidecredits = true
    hidecopyright = false
    series = true
    rtl = false
    colorscheme = "auto"
    maxSeeAlsoItems = 5
    math = true

## 配置 utteranc评论,教程参考 https://utteranc.es/
[params.utteranc]
  enable = true
  repo = "StarShangGP1/starshanggp1.github.io"
  issueTerm = "pathname"
  theme = "github-light"

# Social links
[[params.social]]
    name = "Github"
    icon = "fa fa-2x fa-github"
    weight = 1
    url = "https://github.com/StarShangGP1" 
[[params.social]]
    name = "RSS"
    icon = "fa fa-2x fa-rss"
    weight = 6
    url = "index.xml"
    type = "application/rss+xml"

[languages.zh-cn.menu]
    [[languages.zh-cn.menu.main]]
        name = "文章"
        weight = 1
        url = "posts/"
    [[languages.zh-cn.menu.main]]
        name = "关于"
        weight = 2
        url = "about/"